version: "3.8"

services:
  r2d2:
    container_name: r2-d2
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: "/r2-d2"
    depends_on:
      - dynamodb
    networks:
      - lttkgp-network
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    ports:
      - "8001:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    networks:
      - lttkgp-network

volumes:
  dynamodb_data:

networks:
  lttkgp-network:
    external: true
