swagger: "2.0"
info:
  description: Facebook connector for C-3PO that manages & exposes Facebook group data
  title: R2-D2
  version: 0.1.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

paths:
  /healthz:
    get:
      operationId: checkHealth
      produces:
        - text/plain
      responses:
        '200':
          description: OK message
          schema:
            type: string
            enum:
              - OK